### ISSUE TITLE
threestudio?

### ISSUE THREAD

**Issue by reynoldscem** [XinYu-Andy/Classifier-Score-Distillation#1]
Great work. Is your codebase based upon threestudio? When do you intend to release, either way?

**Comment by XinYu-Andy** [comment]
> Great work. Is your codebase based upon threestudio? When do you intend to release, either way?

Thanks for your interest in our work! Our code is based on threestudio, and we plan to release it both in this repo and as a separate branch in threestudio. We're aiming to make it public around the end of November.

**Comment by reynoldscem** [comment]
Brilliant! Very much looking forward to it.

**Comment by XinYu-Andy** [comment]
> Brilliant! Very much looking forward to it.

Hi, the code is released now, at [this repo](https://github.com/CVMI-Lab/Classifier-Score-Distillation).

**Comment by reynoldscem** [comment]
@XinYu-Andy Amazing, thank you!
